### ISSUE TITLE
UFOconvert: Sorting lib entries in glif

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/pysilfont#1]
Some tools that work on UFOs store data in glif lib dicts. Examples:

com.typemytype.robofont.guides
com.typemytype.robofont.mark

Unfortunately other tools (such as fontforge) do not respect the original order within the dicts and rewrite them out of order, even on glyphs that were not touched.

Could UFOconvert please always normalise the dicts in the lib to be ordered alphabetically by key, as robofont does?

**Comment by DavidRaymond** [comment]
Will look into this - currently the code just treats this as plain xml data rather than handling as a plist - but it needs extending to do that anyhow!

**Comment by DavidRaymond** [comment]
From looking at [#2](https://github.com/silnrsi/pysilfont/issues/2). I think all <dict> elements should be sorted alphabetically wherever they occur.

**Comment by DavidRaymond** [comment]
Fixed in [Fixes to issues #1 - #4](https://github.com/silnrsi/pysilfont/commit/6b7a9514bb57b8f57b640e3dcbb81c35d9f0a0b3) by adding code to sort all \<dict\> elements.
