### ISSUE TITLE
make_fea should parse and generate flat fea

### ISSUE THREAD

**Issue by mhosken** [silnrsi/pysilfont#12]
Rather than generating partial fea that requires interleaving of various files and doesn't support conditional components, make_fea could be written to parse the included fea and produce a flat fea file that can be compiled using any conventional fea compiler. This would allow us to embrace and extend fea to our choosing.

This will probably require adding fea generation to fonttools. As to whether they want that upstream is up to them.

**Comment by bobh0303** [comment]
Perhaps closing this issue was valid, but a reason for the action would be helpful.

I believe the sentiment expressed by this issue -- especially in the first paragraph -- is still a valid concern, though maybe it has been included elsewhere?

**Comment by mhosken** [comment]
I closed it because that is precisely what is happening in the development of psfmakefea. I realise there may not be much to show for it. But neither do I consider this an issue we need to be tracking any more.
