### ISSUE TITLE
FFCopyGlyphs doesn't support glyph references

### ISSUE THREAD

**Issue by mhosken** [silnrsi/pysilfont#13]
When using glyphs that are composites of other glyphs as source glyphs, the positions and sizes get all messed up at best.

**Comment by DavidRaymond** [comment]
Was this fixed by https://github.com/silnrsi/pysilfont/commit/b4d50fd55cf70ae7d0c650273cbcef5ce7a8e627#diff-c6e1b1d469eb15bc94195041ad77f5cf

**Comment by DavidRaymond** [comment]
Understand this was fixed by b4d50fd
