### ISSUE TITLE
install UFOexportAnchors

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#14]
please include UFOexportAnchors in the scripts that are installed -- it is needed in UFO workflow to build Graphite fonts.

**Comment by n7s** [comment]
The process involves copying from scripts/ to lib/silfont/scripts for the file to be picked up by packaging.

**Comment by n7s** [comment]
or from somewhere else...

**Comment by DavidRaymond** [comment]
Now done
