### ISSUE TITLE
why 3 classes of scripts?

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#17]
pysilfont appears to have 3 classes of scripts:

- those that are installed
- those in scripts folder
- those in scripts/examples folder

What are the distinctions between these three, and do we need all three?

**Comment by nrsiward** [comment]
In the 2017-05-10 Font Tech meeting, we decided to install more scripts and combine the remaining ones. Those not installed will be ones which are: examples for developers, quick hacks for a specific need, project specific ones which require modification, or not executable from the command line.
