### ISSUE TITLE
UFOexportAnchors fails with extra or missing glyphs

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#19]
UFOexportAnchors reads the public.glyphOrder in the lib.plist in order to figure out the glyph indexes to include in the XML file. However there are three cases that are not handled properly:
1) public.glyphOrder includes glyphnames that are not actually in the font
2) the font contains glyphs that are not mentioned in public.glyphOrder.
3) public.glyphOrder is not present.

All of these cases are allowed by the [spec](http://unifiedfontobject.org/versions/ufo3/lib.plist/), which says:

> This key is used for representing the user’s preferred glyph order in the font.... This data is optional.
The glyph order is stored as a list of glyphs names. Glyph names must not occur more than once. Glyph names in the font may not appear in the order. The order may contain glyphs that are not in the font.

Current behavior of UFOexportAnchors:
In case (1) the program crashes.
In case (2) the extra glyphs not mentioned in public.glyphOrder are not included in the output XML file.
Case (3) is untested (by me) but from looking at the code I'll guess the output XML contains no glyphs at all.

**Comment by bobh0303** [comment]
While rewriting, I suggest adding code to detect the error condition mentioned in the spec:
>Glyph names must not occur more than once.

**Comment by jvgaultney** [comment]
It can be easy for public.GlyphOrder and the UFO contents to get out of sync. What's really needed is to make an integrity check tool (UFOcheck) that among other things, could compare public.GlyphOrder and contents.plist and report discrepancies.  JIRA issue created https://jira.sil.org/browse/FTLS-318

**Comment by bobh0303** [comment]
In as much as UFO3 explicitly states that the public.glyphOrder does not need to match the glyph repertoire in the font, our tools should handle that.

**Comment by DavidLRowe** [comment]
Case (3) probably would also have crashed. Now uses empty public.glyphOrder list.
Case (1) generates warning that glyph is "in public.glyphOrder list but absent from UFO"
Case (2) generates warning that glyph "in UFO but not in public.glyphOrder list" and these glyphs are included after those in the public.glyphOrder list.
If a glyph name is included more than once in the public.glyphOrder list, a warning is issued:
"At least one duplicate name in public.glyphOrder". This will also generate one or more "in public.glyphOrder list but absent from UFO" warnings.

**Comment by bobh0303** [comment]
> If a glyph name is included more than once in the public.glyphOrder list, a warning is issued

I'd suggest this is a fatal error. There is no way to guess what the caller really intended, and UFO3 says glyphs "must not" occur twice in the list.
