### ISSUE TITLE
UFOconvert: Sorting lib entries in lib.plist

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/pysilfont#2]
Please sort dicts in lib.plist alphabetically by key. This will avoid unwanted changes to private libs such as com.typemytype.robofont.sort

**Comment by DavidRaymond** [comment]
This should happen by default, so I'll check why it is not working.

**Comment by DavidRaymond** [comment]
Just to check - are you referring to dicts within the overall plist dict?  Currently the main plist dict is sorted alphabetically, but not dicts within individual entries.

I presume dicts at any level should be sorted alphabetically.

**Comment by DavidRaymond** [comment]
Fixed in [Fixes to issues #1 - #4](https://github.com/silnrsi/pysilfont/commit/6b7a9514bb57b8f57b640e3dcbb81c35d9f0a0b3) by adding code to sort all \<dict\> elements.
