### ISSUE TITLE
turn ufo2ttf into a proper pysilfont app

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#21]
In particular, parameter handling and chaining.

**Comment by nrsiward** [comment]
I've added ufo2ttf.py to the ufo2ttf branch in the repo. See the TODO comments at the top of the file for further work.

**Comment by anthrotype** [comment]
I'm happy to see you are trying out ufo2ft!
Please let us know if you encounter any issues or have feature requests.
Also note that the current API should not be considered stable and may change in the near future.
Cheers!

**Comment by nrsiward** [comment]
This is mostly done in commit 47234c1

**Comment by bobh0303** [comment]
Is there anything else to do or can this be closed now?

**Comment by nrsiward** [comment]
I asked DR to check it to be sure the pysilfont-ification is correct.

**Comment by DavidRaymond** [comment]
Looks fine to me
