### ISSUE TITLE
UFObuildComp assumes that all glyphs have an advance width set

### ISSUE THREAD

**Issue by madig** [silnrsi/pysilfont#22]
Trufont or one of the underlying libraries do not save the `<advance width="..."/>` element if it is set to zero. This trips up https://github.com/silnrsi/pysilfont/blob/master/lib/silfont/scripts/UFObuildComp.py#L143 and throws an uncaught exception. Suggestion: element not present -> width is zero.

**Comment by DavidRaymond** [comment]
Makes sense!  Will pick that up with #23

**Comment by DavidRaymond** [comment]
Fixed in https://github.com/silnrsi/pysilfont/commit/4f6080cdb856efa743fd2e7d1f954478fe2a5908
