### ISSUE TITLE
Ufoconvert: scrub editor-specific data?

### ISSUE THREAD

**Issue by madig** [silnrsi/pysilfont#24]
I noticed that while using Glyphs, the saved UFO afterwards contains many Glyphs-specific parameters and such, like the date of the last change of a glyph. I'd like to scrub all that before committing it, as it just bloats the diff. Would UFOconvert be the right tool for that?

**Comment by davelab6** [comment]
UFO normalization is done by another package iirc

**Comment by n7s** [comment]
UFOconvert is the normalization tool written by @DavidRaymond.  The name is slightly unclear. 
You might want to use the OSX "workflow" (in https://github.com/silnrsi/pysilfont/tree/master/actionsosx).

**Comment by moyogo** [comment]
Scrubing private lib keys should not be the default behaviour of a UFO normalizer.

I guess what you want to do is something like this:

```python
import sys
import defcon

ufo = defcon.Font(sys.argv[1])
domains = sys.argv[2:]

objects = [ufo]
for layer in ufo.layers:
    objects.extend(glyph for glyph in layer)
for obj in objects:
    for lib_key in list(obj.lib):
        for domain in domains:
            if lib_key.startswith(domain):
                del obj.lib[lib_key]
ufo.save()
```
and then normalize.

**Comment by jvgaultney** [comment]
When possible we leave private keys in place, as that can be very helpful when using some specific tools (esp. Glyphs). Some tools also read and use private keys from other apps. This specific issue - that Glyphs tends to mark every glyphs as changed if it reads, modifies, then exports a UFO - can be solved by tweaking a hidden parameter in Glyphs. See: https://forum.glyphsapp.com/t/has-anyone-had-problems-working-with-glyphs-files-on-github/4077

**Comment by madig** [comment]
Thanks for the replies. I guess I'm going to apply all of them ;)
