### ISSUE TITLE
misleading help messages

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#25]
Using `psfmakewoffmetadata` as an example (though this may apply to many of the scripts), the long help message is currently:
```
usage: psfmakewoffmetadata [-h] -n PRIMARYNAME -i ORGID [-f FONTLOG] [-l LOG]
                           [-d] [-q] [-p PARAMS]
                           font

Make the WOFF meatadata xml file based on input UFO and FONTLOG.txt

positional arguments:
  font                  Source font file

optional arguments:
  -h, --help            show this help message and exit
  -n PRIMARYNAME, --primaryname PRIMARYNAME
                        Primary Font Name
  -i ORGID, --orgid ORGID
                        orgId
  -f FONTLOG, --fontlog FONTLOG
                        FONTLOG.txt file
  -l LOG, --log LOG     Log file
  -d, --defaults        Display help with info on default values
  -q, --quiet           Quiet mode - only display errors
  -p PARAMS, --params PARAMS
                        Other parameters
```
According to the short usage message, `-n` and `-i` appear to be required, but in the longer description of the arguments they are listed in the section called `optional arguments`.   Can this be improved or is it out of our control?

**Comment by DavidRaymond** [comment]
I'd noticed that as well - suspect this might be the first script that has had -- arguments that are required.  The help text is generated automatically by argparse, and this issue with argparse is recognised - eg see http://bugs.python.org/issue9694

Some solutions, like adding extra argument groups, might be hard to implement within the execute() framework.  Changing the title from "optional arguments" to something else might be fairly doable - eg "other arguments".

**Comment by DavidRaymond** [comment]
Adding code to change "optional arguments" to "other arguments".

**Comment by DavidRaymond** [comment]
The help now says "other arguments".
(This was changed a while ago!)
