### ISSUE TITLE
pfsmakewoffmetadata needs -o option to specify output file

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#27]
If we intend to use `psfmakewoffdata` to build the woff metadata on the fly from a wscript, we need to be able to override the output file path and name. Normally this would be via `-o filename` option. 

(Some may argue that the woff metadata file should be built at preflight and then checked into the repo. While I'm not inclined to favor this approach, if we wanted to go this route then we need to add license text to the generated metadata file).

**Comment by jvgaultney** [comment]
Not sure why the metadata file would need to be anywhere other than in source/, and our internal standards say it should be there. I do feel it that the resulting file *should* be checked in, as some projects may wish to use the script and some may not. IOW there should be a clear pattern in our projects that all of them have a projectname-WOFF-metadata.xml file in them. It is up to the project whether to construct that file from an script or manually maintain it.

**Comment by DavidRaymond** [comment]
Agreed that for standard NRSI projects there should be no need for a -o option, but could be useful for other pysilfont users, so will add -o when next changing psfmakewoffmetadata

**Comment by DavidRaymond** [comment]
-o option added in commit https://github.com/silnrsi/pysilfont/commit/3b206dc1cd1b1714dc47bbc90a61b59c8d5c0518#diff-735a955e5f0799adb9ab8957276c48a9
