### ISSUE TITLE
UFOconvert: Fixing up <real> elements that FF has rewritten

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/pysilfont#3]
Robofont stores private data in the glif lib that often contains elements such as

<real>1.0</real>

Fontforge, however, likes to change this to

<real>1</real>

It does this even for glyphs that aren't otherwise touched. This has been reported as a FF bug, but who knows when and if it will be fixed. 

So could we please add '.0' to all such elements that have no decimal portion?

**Comment by davelab6** [comment]
Make more noise on the ff issue :)

**Comment by DavidRaymond** [comment]
That's doable.  

May also need to think about other issues with <real> elements - there was some discussion in the past (which I'll have to track down) about level of precision and rounding errors - eg 8.0 ending up ad 7.99999999.  Might any need padding to a specific precision?

The .0 can be added anyhow.

The FontForge issue is [#2276](https://github.com/fontforge/fontforge/issues/2276).

**Comment by DavidRaymond** [comment]
Following Tal's proposals on [UFO Normalization](https://groups.google.com/forum/#!topic/ufo-spec/dIxfPvCTvlY) in the UFO spec Google group and our own internal discussions, I'm implementing changing to <integer>n</integer> whenever a value is an integer.

**Comment by DavidRaymond** [comment]
Fixed in [Fixes to issues #1 - #4](https://github.com/silnrsi/pysilfont/commit/6b7a9514bb57b8f57b640e3dcbb81c35d9f0a0b3)
Also included rounding \<real\> precision to 6 digits, though precision can be changed by parameters
