### ISSUE TITLE
Add script to rename glyphs

### ISSUE THREAD

**Issue by madig** [silnrsi/pysilfont#30]
The main use would be to mass-rename glyphs in a UFO, using a custom list with a "Unicode value\tGlyph name" format, a FontLab-style .nam, or Glyphs' https://github.com/schriftgestalt/GlyphsInfo as the database.

**Comment by bobh0303** [comment]
What about unencoded glyphs (i.e., those without Unicode values)? These would not be included in any of the suggested input formats.

**Comment by madig** [comment]
Hm, I'd expect the tool to rename glyphs according to the associated Unicode value. If there is no Unicode value, no renaming takes place.

**Comment by bobh0303** [comment]
Recently added `psfrenameglyphs` can be used to rename glyphs within a UFO. The input is a csv file in `oldname,newname` format so not exactly what you were looking for. However it could be used to implement the rename you seek by crafting the appropriate csv.
