### ISSUE TITLE
psfmakefea: need explicit class generated for each markClass

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#37]
Consider the following 3 glyphs:

- `gBase` has U anchor
- `gMark1` has _U and U anchors
- `gMark2` has _U

There are three possible classes that could be needed:

- `@U` -- contains all bases with U (i.e., gBase)
- `@U_MarkBase` -- contains all marks with U (i.e., `gMark1`)
- `@_U` -- contains all marks with _U (i.e., `gMark1` and `gMark2`)

The first two are implemented, though I'm not sure of the need for `@U` since in the feax expression:
```
    pos base @U mark @_U;
```
the `@U` gets expanded out by psfmakefea.

The second two are needed to create the mark filter sets for mark-to-mark lookups:
```
@MarkFilter_U = [@U_MarkBase @_U];
lookup mark_to_mark_above {
    lookupflag UseMarkFilteringSet @MarkFilter_U;
    ...
```

Thus we need the `@_U` to be generated by psfmakefea.

**Comment by bobh0303** [comment]
This might be my mistake. awaiting a fresh build to test

**Comment by bobh0303** [comment]
OK, if you use Harmattan-Regular.ufo and try to compile this test.feax:
```
@MarkFilter_diaA = [@diaA_MarkBase @_diaA];
lookup mark_to_mark_above {
  lookupflag UseMarkFilteringSet @MarkFilter_diaA;
  pos mark @diaA_MarkBase mark @_diaA;
} mark_to_mark_above;
```
what you'll see in the output fea is:
```
@MarkFilter_diaA = [@diaA_MarkBase @_diaA];
lookup mark_to_mark_above {
    lookupflag UseMarkFilteringSet @MarkFilter_diaA;
    pos mark shadda_damma-ar <anchor 228 2044> mark @_diaA;
    ...
```
but the @_diaA class is never defined. 

I thought this was working a week or two ago, and we were getting something like
```
@MarkFilter_diaA = [ [ _glyph-list-from @diaA_MarkBase_ ] [ _glyph-list-from-@_diaA_ ] ];
```
but that isn't what is happening now.

**Comment by bobh0303** [comment]
Apparently fonttools compiler allows explicit access to the markClasses. At least the `@MarkFilter_diaA` definition mentioned above compiles [correctly] with fonttools, whereas AFDKO complains that `@_diaA` is undefined.

Thus this is actually a difference between fonttools and AFDKO.

**Comment by anthrotype** [comment]
please let us know if this is a bug in feaLib, thanks

**Comment by bobh0303** [comment]
@anthrotype While it is a difference from AFDKO, I'd consider it an improvement rather than a bug. Thanks.

**Comment by bobh0303** [comment]
afaik we aren't awaiting any further work on this.
