### ISSUE TITLE
psfnormalize deletes data directory

### ISSUE THREAD

**Issue by madig** [silnrsi/pysilfont#40]
1. Get https://github.com/daltonmaag/ubuntu
2. Add license metadata to some UFO
3. Normalize it

The data subdirectory that holds hinting data is gone afterwards. I don't think this should happen.

**Comment by bobh0303** [comment]
Indeed, the `data` folder is part of the UFO3 spec so should be retained unless normalizing to UFO2. 

Since psfnormalize cannot know the content or format of files under `data`, do we conclude that psfnormalize should simply retain the data exactly as is (sans empty subfolders)? Or should we try to be more clever and, for example, try to detect XML files under `data` and normalize them?

**Comment by madig** [comment]
Hm. I suppose that playing dumb may be a good start. In e.g. the Ubuntu font (see repo above), the data directory stores ttx blobs of VTT hinting data and the maxp table in XML form. I don't know if this would confuse code that worked on it (vttLib), but it would at least lead to commit churn...

**Comment by anthrotype** [comment]
The data folder is for arbitrary private stuff. You need to keep it as it is

> Authoring tools are responsible for their own sections of the data directory and they must not delete or modify any other sections of the data directory belonging to other tools unless given permission to do so.

http://unifiedfontobject.org/versions/ufo3/data/

**Comment by bobh0303** [comment]
If psfnormalize were able to locate and normalize xml text files under `data`, such processing would probably need to be disabled by default and enabled with a command-line parameter, thus providing the required "permission".  Of course more clever options might exist... providing a default class object to handle items in `data` and allow Authoring tool vendors to provide subclasses for their own data. 

I was just trying to feel out whether anyone thinks we should go down those kinds of roads. I'm happy with the "keep `data` as it is" strategy -- certainly easier!

**Comment by DavidRaymond** [comment]
There are various aspects of improving UFO 3 support outstanding, and the data directory (as well as the images directory) are included.  With more interest in UFO 3 nowadays, I expect this will move up the priority list.  Support for retaining the data directory should be relatively easy to implement.

**Comment by DavidRaymond** [comment]
data/images directories are now preserved.
Fuller support may be added later.
