### ISSUE TITLE
psfrenameglyphs will normalize everything

### ISSUE THREAD

**Issue by madig** [silnrsi/pysilfont#43]
I'm trying to clean up four (version 3) UFOs (https://github.com/daltonmaag/ubuntu/issues/5#issuecomment-348699789) that contain box drawing glyphs named e.g. `SF540000.001`. I want to remove the .001 suffix and assign them Unicode values.

psfrenameglyphs doesn't just rename glyphs, but will also try to normalize everything, leading to some damage along the way (data directory gone, many seemingly pointless changes in fontinfo.plist). I'd prefer if the tool simply changed what's needed to rename glyphs and left the rest alone.

**Comment by DavidRaymond** [comment]
The default for checkfix is now check, and data/images directories are preserved.
It will still normalise in terms of xml formatting, but that is by design.
