### ISSUE TITLE
psfmakefea to default to checkfix=none

### ISSUE THREAD

**Issue by mhosken** [silnrsi/pysilfont#44]
Please make psfmakefea default to checkfix=none without the user having to do anything.

I can't work out how to break into the default such that this is possible from an application. There's a lot of code there that makes a complex structure rather than a simple dictionary initialised to defaults and updated from what comes in from the -p dictionary. Could save 100 lines of code perhaps?

**Comment by bobh0303** [comment]
Did you try the code as of fceb9bd6? David has (a) fixed the problem that psfmakefea wasn't handling the params correctly, and (b) set the system-wide default to checkfix=check.  The result is that a UFO that doesn't pass some of the checks won't stop the program from running.

**Comment by DavidRaymond** [comment]
As far as the structure is concerned, there may well be a better way of handling the parameters, but [parameters.md](https://github.com/silnrsi/pysilfont/blob/master/docs/parameters.md#parameter-sets) explains why a simple dict would not have worked.

**Comment by DavidRaymond** [comment]
Not needed now checkfix defaults to check
