### ISSUE TITLE
-p checkfix=check should never reject a font

### ISSUE THREAD

**Issue by mhosken** [silnrsi/pysilfont#45]
Ensure that however bad the check failure, e.g. lib.plist missing or something else that means the check can't run, that the check will complete and pass control to the application. checkfix=check must never reject a font, only report any problems it can find.

**Comment by bobh0303** [comment]
Other than psfmakefea (which was just fixed) do you know of a situation where this is not the case? Or are you asking for a code review? Or something else?

**Comment by DavidRaymond** [comment]
checkfix=check won't reject a font.  The problem was with psfmakefea (which is now fixed) in that the parameters were not passed to the Ufont object, so it worked on the default which was checkfix=fix.

(checkfix=check is now the default anyhow)

**Comment by DavidRaymond** [comment]
(Correction - there was a bug, so Martin was correct that it did fail if lib.plist was missing.  Now fixed)

**Comment by DavidRaymond** [comment]
Fixed with fceb9bd6d97590dfe0fe0f5e63c82ef72abb1f82 and 720756a6518278ad393e0befbed3da45223ef0ba
