### ISSUE TITLE
psfsyncmeta: com.schriftgestaltung.font.glyphOrder is incorrect

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#47]
According to https://forum.glyphsapp.com/t/which-is-the-correct-glyphorder-key/7801 the correct keyname is `com.schriftgestaltung.glyphOrder`.

The keyname  `com.schriftgestaltung.font.glyphOrder` is a remnant of an old bug and should not be used.

At present `psfsyncmeta` is requiring both keys. Instead, we should migrate the old name to the new one if the new doesn't exist, otherwise remove the old one.

**Comment by DavidRaymond** [comment]
Will update psfsycnmeta (and psfcopymeta) so that com.schriftgestaltung.font.glyphOrder is no longer required or synced.  Any copying to com.schriftgestaltung.glyphOrder should be manual rather than build in to the tools.
