### ISSUE TITLE
Installation warns that fonttools is not installed even when it is

### ISSUE THREAD

**Issue by jvgaultney** [silnrsi/pysilfont#49]

**Comment by anthrotype** [comment]
https://github.com/silnrsi/pysilfont/blob/master/setup.py#L20

the name of the nodule is "fontTools" not "fonttools"

**Comment by n7s** [comment]
also designspace is probably designSpaceDocument instead but since it will be absorbed into fontTools that dependency check may not be needed any longer.

**Comment by DavidRaymond** [comment]
Corrected in 0fa2f89
