### ISSUE TITLE
psfexportanchors against fontforge generated ufo

### ISSUE THREAD

**Issue by mhosken** [silnrsi/pysilfont#50]
psfexportanchors crashes for lack of Ufont.lib with or without -g specified on the command line.

The .ufo has been normalized from fontforge export using psfnormalize --version=3. But lib.plist is not required by ufo3 (or 2).

Suggestion is for -g is that if lib.plist is missing, then psfexportanchors should give a warning and continue without -g.

**Comment by DavidRaymond** [comment]
d1e1a65  fixes the crash problem.  Improved logging will be done later
