### ISSUE TITLE
shouldn't Pipfile (and Pipfile.lock) specify Python 2.7 ?

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#60]
https://github.com/silnrsi/pysilfont/blob/4d994d23d356df1f20cc74cb87354c0e4637f359/Pipfile#L41

IMO: since we are currently using py 2.7 for pysilfont, the pipfiles should specify that, not py 3.5.  In the branch where we start making changes to support py 3. then we can change the pipfiles accordingly.

**Comment by n7s** [comment]
This was initially set up to help the py3 transition for developers, not for user deployment (which we are currently doing via the LP recipe), the default was set to 3.5.  Easy to change back and forth.
