### ISSUE TITLE
OTS finds an error with Graphite tables after using `psfdeflang`

### ISSUE THREAD

**Issue by devosb** [silnrsi/pysilfont#63]
With the [NLCI Tamil fonts](https://github.com/nlci/taml-font-thiruvalluvar) language specific fonts are created so users do not need to set a font feature in their application. The command `ttfdeflang` was used to create the fonts. In testing the replacement for `ttfdeflang`, which is `psfdeflang`, the fonts are created, but OTS finds an error
```
ERROR: Sill: 7 incorrect offsets into settings
ERROR: Table discarded
```

**Comment by devosb** [comment]
However, the issue does not seem to occur with [Shimenkan](https://github.com/silnrsi/font-shimenkan) which also used `psfdeflang`.

**Comment by jvgaultney** [comment]
Shimenkan does not have Graphite tables, and this is Graphite-related.
