### ISSUE TITLE
ufonormalizer and psfnormalize produce different results

### ISSUE THREAD

**Issue by probonopd** [silnrsi/pysilfont#69]
[ufonormalizer](https://github.com/unified-font-object/ufoNormalizer) and [psfnormalize](https://github.com/silnrsi/pysilfont) produce different results.

This kinda defeats the purpose, doesn't it?

To reproduce:

In a local test git repository, normalize a font with `psfnormalize`, then `git commit`, then normalize the already normalized font with `ufonormalizer`. You would expect no changes a `git diff` will show plenty of changes.

Including trivial ones such as (`psfnormalize`)

```
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```
vs. (`ufonormalizer`)
```
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
```

I think both tools should either produce 100% the same "normalization", or else it is not a "normalization". Maybe having 2 such tools just complicates matters and one should be retired?

Reference:
https://github.com/unified-font-object/ufoNormalizer/issues/70

**Comment by jvgaultney** [comment]
Response:

https://github.com/unified-font-object/ufoNormalizer/issues/70
