### ISSUE TITLE
psfrenameglyphs not updating com.schriftgestaltung.Glyphs.ComponentInfo

### ISSUE THREAD

**Issue by bobh0303** [silnrsi/pysilfont#72]
I have just committed code to psfrenameglyphs that should be adjusting any `com.schriftgestaltung.Glyphs.ComponentInfo` references to renamed glyphs in each glif lib. See commit b41bb8cd

However, the changes the code makes in the ComponentInfo are not being written to the output font.

To reproduce:
- check out `extension-rename` branch of [font-lateef](https://github.com/silnrsi/font-lateef)
- save [rename-short.txt](https://github.com/silnrsi/pysilfont/files/5240874/rename-short.txt) to the `source` folder
- run the command as `psfrenameglyphs -p scrlevel=I -i rename-short.txt masters/Lateef-Light.ufo`  (nb: not Regular)
- notice the 2nd and 3rd onscreen Info messages starting `renamed component` that show the renaming of a component in the glyph `alefHamzaabove-ar.postLamIni.fina`:
```
renamed component base alef-ar.postLamIni.fina to zork in glyph alefHamzaabove-ar.postLamIni.fina layer public.default
renamed component info alef-ar.postLamIni.fina to zork in glyph alefHamzaabove-ar.postLamIni.fina layer public.default
```
(The first is when the glyph outline block is updated ([line 260](https://github.com/silnrsi/pysilfont/blob/b41bb8cd85cb35e833e40a723e326103069ec9ef/lib/silfont/scripts/psfrenameglyphs.py#L260)), the second from when the ComponentInfo is updated ([line 268](https://github.com/silnrsi/pysilfont/blob/b41bb8cd85cb35e833e40a723e326103069ec9ef/lib/silfont/scripts/psfrenameglyphs.py#L268)).

So it is clear that the code adjusted the reference from `alef-ar.postLamIni.fina` to `zork` in both the glyph outline and the ComponentInfo block.
- inspect the output .glif file (`masters/Lateef-Light.ufo/glyphs/alefH_amzaabove-ar.postL_amI_ni.fina`) for glyph `alefHamzaabove-ar.postLamIni.fina`
- notice the actual glyph outline component was changed:
```
  <outline>
    <component base="zork"/>       <<<==== correct
    <component base="_hamza" xOffset="179" yOffset="1227"/>
  </outline>
```
but the change to ComponentInfo wasn't actually saved:
```
      <key>com.schriftgestaltung.Glyphs.ComponentInfo</key>
      <array>
        <dict>
          <key>alignment</key>
          <integer>-1</integer>
          <key>index</key>
          <integer>0</integer>
          <key>name</key>
          <string>alef-ar.postLamIni.fina</string>      <<<==== not correct
        </dict>
        <dict>
          <key>alignment</key>
          <integer>-1</integer>
          <key>index</key>
          <integer>1</integer>
          <key>name</key>
          <string>_hamza</string>
        </dict>
      </array>
```

**Comment by DavidRaymond** [comment]
.getval() just gets a copy of the data, so changes to that don't affect the actual data (glyph.lib in the case).

With lib, to update it the xml element needs updating.

Commit 2e0abb7 fixes this.
