### ISSUE TITLE
Syntax warning from the Ubuntu packaging on focal 20.04

### ISSUE THREAD

**Issue by n7s** [silnrsi/pysilfont#74]
Setting up python3-pysilfont (1.5.1.dev0-0~621-snapshot-202010060346~ubuntu20.04.1) ...
/usr/lib/python3/dist-packages/silfont/scripts/psfchangegdlnames.py:46: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if outfile is not "" and os.path.splitext(outfile)[1] == "" : # if no extension on outfile, assume a dir was meant
/usr/lib/python3/dist-packages/silfont/scripts/psfchangegdlnames.py:52: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if outdir is "" :
/usr/lib/python3/dist-packages/silfont/scripts/psfcopymeta.py:49: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ftag is 'real' : ftext = processnum(ftext,precision)
/usr/lib/python3/dist-packages/silfont/scripts/psfcopymeta.py:56: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if ttag is 'real' : ttext = processnum(ttext,precision)
/usr/lib/python3/dist-packages/silfont/scripts/psfsetassocfeat.py:35: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  if value is not "" :
/usr/lib/python3/dist-packages/silfont/scripts/psfsyncmeta.py:184: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if mtag is 'real' : mtext = processnum(mtext,precision)

**Comment by n7s** [comment]
This is with python3.8 (on focal 20.04)

**Comment by bobh0303** [comment]
Did you try the suggestions (ie using `--` and `!=`)? If that fixes it, commit ;-)
