### ISSUE TITLE
Fields in FONTLOG.txt are not found

### ISSUE THREAD

**Issue by devosb** [silnrsi/pysilfont#77]
When running `psfmakewoffmetadata --populateufowoff ...` the command requires that the `FONTLOG.txt` file have at least two sections, one headed by

```
Basic Font Information
----------------------
```
and the other by
```
Acknowledgements
----------------
```
But the new style of repo documentation (such as FONTLOG.txt) is
```
## About this project
```
and
```
## Acknowledgements
```

**Comment by jvgaultney** [comment]
In the new markdown-based documentation there is no implied or expected structure, so `--populateufowoff` can't guess at the data. If you have already switched the project to use the new docs you can temporarily add those expected headers for the one-time `--populateufowoff` process.

A simpler, faster process would be to not use `--populateufowoff` at all. Add the fields to the UFO manually, using other projects (such as Lisu Bosa) as a guide to how those plist keys should be formed.
