### ISSUE TITLE
make logs folders test/creation more robust

### ISSUE THREAD

**Issue by n7s** [silnrsi/pysilfont#78]
It might be the special environment of the CI, but I've noticed some projects randomly failing in certain build or test steps because of a results/logs folder already present. For example:

Traceback (most recent call last):
  File "/usr/local/bin/psfwoffit", line 8, in <module>
    sys.exit(cmd())
  File "/usr/local/lib/python3.8/dist-packages/silfont/scripts/psfwoffit.py", line 95, in cmd
    def cmd() : execute('FT',doit, argspec)
  File "/usr/local/lib/python3.8/dist-packages/silfont/core.py", line 514, in execute
    os.mkdir(logpath)
FileExistsError: [Errno 17] File exists: '/opt/buildagent/work/f9a523e00d55b8df/results/logs'

Maybe something can be done to test for the presence of an existing logs folder in a different way?

**Comment by jvgaultney** [comment]
This has been a longstanding random problem on the CI (only) that hints at a race condition. I've never seen it happen elsewhere. If you then rerun the build it seems to then work fine. Some suggestions from stack exchange:
https://stackoverflow.com/questions/12468022/python-fileexists-error-when-making-directory

**Comment by DavidRaymond** [comment]
This will only happen after a fresh clone of a font repo, since at that stage there will not be a logs folder. Common on the CI but rarer otherwise.
Changing `os.mkdir(logpath)` to `os.makedirs(logpath, exist_ok=True)` in core.py should fix this anyhow.

**Comment by DavidRaymond** [comment]
Change pushed: e173c6d73aeaf53e26c1fa240ebe93fd0b144284 which should resolve this.
