### ISSUE TITLE
psfmakefea fails when there are different substitution types

### ISSUE THREAD

**Issue by LynnKirby** [silnrsi/pysilfont#86]
**The error**

The following is valid in normal .fea files but raises an error when using psfmakefea. Splitting the two kinds of substitutions into separate lookup block works fine. The error occurs when the two kinds are in the same block.

```afdko
feature test {
  sub A by B;
  sub C by D E;
} test;
```

<details><summary>Traceback</summary>
<p>

```
  File "D:\projects\feax-error\.venv\Scripts\psfmakefea.exe\__main__.py", line 7, in <module>
  File "D:\projects\feax-error\.venv\Lib\site-packages\silfont\scripts\psfmakefea.py", line 368, in cmd
    def cmd(): execute(None, doit, argspec)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\feax-error\.venv\Lib\site-packages\silfont\core.py", line 647, in execute
    newfont = fn(args)
              ^^^^^^^^
  File "D:\projects\feax-error\.venv\Lib\site-packages\silfont\scripts\psfmakefea.py", line 359, in doit
    doc_fea = p.parse(args.input)
              ^^^^^^^^^^^^^^^^^^^
  File "D:\projects\feax-error\.venv\Lib\site-packages\silfont\feax_parser.py", line 82, in parse
    return super(feaplus_parser, self).parse()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\feax-error\.venv\Lib\site-packages\fontTools\feaLib\parser.py", line 105, in parse
    statements.append(self.parse_feature_block_())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\projects\feax-error\.venv\Lib\site-packages\fontTools\feaLib\parser.py", line 1745, in parse_feature_block_
    self.parse_block_(block, vertical, stylisticset, size_feature, cv_feature)
  File "D:\projects\feax-error\.venv\Lib\site-packages\fontTools\feaLib\parser.py", line 2032, in parse_block_
    self.ast.MultipleSubstStatement(
  File "D:\projects\feax-error\.venv\Lib\site-packages\silfont\feax_ast.py", line 197, in __init__
    lenglyphs = len(self.glyph.glyphSet())
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'glyphSet'
```

</p>
</details>

**The problem**

feaLib makes inconsistent use of glyphs as name strings and glyph-containing objects (`GlyphName` and friends). The doc strings for glyph-containing object classes says `glyphSet()` returns a tuple of glyph-containing objects but they actually return a tuple of strings. Also, many doc strings of feaLib AST classes say they require a glyph-containing object but internally they handle name strings as well.

When feaLib parses a block (`parse_block_()`), it normalizes blocks with both single and multiple substitutions into blocks with only multiple substitution nodes. When it creates `MultipleSubstStatement` nodes, the glyphs are provided by `glyphSet()`, which gives name strings not glyph-containing objects. This works for the feaLib-defined node type since it handles name strings. But the feax version fails because it only handle glyph objects.

---

~~I don't know on which side this problem should be fixed, so I'll be creating a fontTools issue as well.~~

I should have looked at the issue tracker before saying that. They are aware of the issue ([fonttools/fonttools#2748](https://github.com/fonttools/fonttools/issues/2748)) but work seems to be stalled for a year (https://github.com/fonttools/fonttools/pull/2753).

**Comment by bobh0303** [comment]
Thank you, Lynn, for this helpful report.

I'm not sure when we'll get to fixing it, but in any case we may need to visit it again if/when fonttools resolves their issues.

In the meantime, and you probably already know, you can work around the problem by separating the rules using lookup blocks: 

```
feature test {
  lookup x1 {
    sub A by B;
  } x1;
  sub C by D E;
} test; 
```

The resulting GSUB structure will involve two lookups instead of one, but should function the same.
