### ISSUE TITLE
FTML builder aborts with full width variants of ASCII characters if using Glyphs.App names

### ISSUE THREAD

**Issue by devosb** [silnrsi/pysilfont#91]
For U+FF01 FULLWIDTH EXCLAMATION MARK the Glyphs.App XML character database has
```
<glyph unicode="FF01" name="exclam.full" category="Punctuation" production="uniFF01" altNames="exclammonospace" description="FULLWIDTH EXCLAMATION MARK" />
```
This pattern is used for other (punctuation and letters) full width forms of ASCII characters. FTML builder interprets the glyph name `exclam.full` as a variant of `exclam` which is encoded at U+0021 EXCLAMATION MARK.  The [FTML builder aborts](https://github.com/silnrsi/pysilfont/blob/master/src/silfont/ftml_builder.py#L399) with the situation of having a basename (exclam In this case) match two different encoded characters.

**Comment by bobh0303** [comment]
The purpose of checking the `basename` for uniqueness is not, at least not first and foremost, to generate the error message, but it is to find the correct FChar object for the glyph in question.  The FChar object is intended to hold data for an abstract character, including the names of the encoded glyph and all its variant glyphs, relevant features and languages. At present the code assumes that glyphs that share the same `basename` are related and all part of the same abstract character -- in which case only one should be encoded (and thus the test).

Your case violates that fundamental assumption. But your proposal would change the assumption to say that glyphs that share the same `ps_basename` would be assumed to be related and should be in a single FChar object.  That would separate `exclam` and `exclam.full` into distinct FChars, which is at least a partial solution to the problem.

For reference, my most recent GlyphData.xml file (from Glyphs 3190 -- 3.2) has 1501 encoded glyphs that contain extensions on the name, using 55 unique extensions. That's quite a few cases that violate the current assumption.

Assuming we go with your proposal, we now have to decide if/how to change the implementation of various methods (e.g. `FTMLBuilder.char()`).

**Comment by bobh0303** [comment]
In case glyph_data.csv doesn't have the production name, I assume the code would revert to current behavior?

**Comment by devosb** [comment]
Yes, if _ps_name_ is not in `glyph_data.csv`, the behaviour should not change.  This happens both when reading the CSV file, where any absence of the _ps_name_ is already handled, and in calling `addChar()`, where the new _ps_basename_ parameter is optional. Although, the _ps_basename_ is only omitted when calling `addChar()` from `charAuto()`, and I cannot find where `charAuto()` is called from, either in this project or in any project that using the FTML Builder.

I did not change the implementation of `FTMLbuilder.char()`. In the case of duplicated basenames between encoded characters, only the first encoded character basename in the CSV file is recorded in the basename dictionary. This is sufficient for all current built FTML files. If both FChar()s need to be accessed by basename, the code can be improved then.
